### PR TITLE
Removed all cross-references

### PR DESCRIPTION
**Pull request by DavidHaslam**
As requested by Teus in email dated 2017-09-25.

A bespoke TextPipe filter was used to implement systematic changes.

### CODE REVIEW

**Comment by DavidHaslam** [comment]
Even after starting afresh from scratch, there are conflicts.

Is this because you made more new commits _after_ I forked ?

**Comment by DavidHaslam** [comment]
@teusbenschop 

If you cannot resolve these conflicts even after I started afresh with a new fork, how are we to proceed?

**Comment by teusbenschop** [comment]
Yes, the team was just working on the Shona text this whole morning. Sorry I had not realized that the commits due to that work this morning, after you forked, would result in merge conflict. Thanks for the pull request. Even this pull request cannot be applied. The web interface says that there's conflicts that cannot be resolved. I have now switched off the commits coming from the whole team, so that there's going to be no commits until midnight. Sorry bro for the extra work! If it would be possible to do one more attempt of fork/update/pull request, all should be going through fine now.

**Comment by DavidHaslam** [comment]
Thanks Teus. Understood. I will indeed give it another go by starting afresh this afternoon.

_Not to worry. These things are all part of the learning curve._

**Comment by teusbenschop** [comment]
Thanks bro, for understanding and for giving it another go!

**Pull request closed without merging**
