### PR TITLE
Removed all cross-references

### PR DESCRIPTION
**Pull request by DavidHaslam**
As requested by Teus in email dated 2017-09-25.

A bespoke TextPipe filter was used to make the systematic changes.

_This time there are no conflicts._

### CODE REVIEW

**Comment by teusbenschop** [comment]
This one worked! Thanks bro!

**Comment by DavidHaslam** [comment]
FIO. After the related merge, here is the character count of the concatenated data.

[merged.usfm.character.frequency.txt](https://github.com/teusbenschop/shona/files/1329442/merged.usfm.character.frequency.txt)

And here is the USFM tag statistics too.

[merged.usfm.tags.count.usfm.txt](https://github.com/teusbenschop/shona/files/1329445/merged.usfm.tags.count.usfm.txt)

**Comment by DavidHaslam** [comment]
btw. It took only **53.5 seconds** to remove all the cross-references by means of TextPipe.

**Comment by teusbenschop** [comment]
That's way faster than it took me to "add" those xrefs: Many many days of work :)

**Pull request merged**
